security:
  basic:
    enabled: true
  user:
    name: simon
    password: 1234
server:
  port: 8761
eureka:
  server:
    enable-self-preservation: false
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/
spring:
  main:
    banner-mode: console